# Generated by Django 5.0.6 on 2024-08-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_owner_orderitem_order'),
    ]

    operations = [
    ]
