# Generated by Django 5.0.6 on 2024-08-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20240824_1934'),
    ]

    operations = [
    ]
