# Generated by Django 5.0.6 on 2024-08-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20240824_2004'),
    ]

    operations = [
    ]
