# Generated by Django 5.0.6 on 2024-08-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20240825_1750'),
    ]

    operations = [
    ]
