# Generated by Django 5.0.6 on 2024-08-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20240826_1400'),
    ]

    operations = [
    ]
