# Generated by Django 5.0.6 on 2024-08-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20240826_1406'),
    ]

    operations = [
    ]
