# Generated by Django 5.0.6 on 2024-09-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_payment_razorpay_order_id'),
        ('products', '0007_subcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
