# Generated by Django 5.0.6 on 2024-09-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_invoice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
