# Generated by Django 5.0.6 on 2024-07-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='null', max_length=10, null=True),
        ),
    ]
