# Generated by Django 5.0.6 on 2024-07-08 07:01

import products.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=products.fields.ResizableImageField(upload_to='media'),
        ),
    ]
